services:
  database:
    image: postgres:17.4-alpine3.21
    container_name: postgres_prod
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    networks:
      - app-network

  migrations:
    build: .
    command: sh -c "npm ci --save-dev && npm run migrate"
    depends_on:
      - database
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    networks:
      - app-network

  web_green: # New application version
    image: mkaltenr/self-study-13-example:app-0.1.0
    container_name: web-green
    depends_on:
      - database
      - migrations
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    networks:
      - app-network

  web_blue: # Current application version
    image: mkaltenr/self-study-13-example:app-0.1.0
    container_name: web-blue
    depends_on:
      - database
      - migrations
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    networks:
      - app-network

  nginx:
    image: nginx:1.27.4-perl
    ports:
      - "80:80"
      - "81:81"
    depends_on:
      - web_green
      - web_blue
    env_file:
      - .env
    volumes:
      - ./nginx-site:/etc/nginx
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data_prod:
